CREATE TABLE administrador (
  idAdmin SERIAL NOT NULL PRIMARY KEY,
  emailAdmin VARCHAR(255) NOT NULL UNIQUE,
  passAdmin VARCHAR(255) NOT NULL
);

INSERT INTO administrador (emailAdmin, passAdmin) VALUES 
  ('admin1@example.com', 'O t5QQx<qSR'),
  ('admin2@example.com', 'O t5QQx<qS?'),
  ('admin3@example.com', 'O t5QQx<qS1'),
  ('admin4@example.com', 'O t5QQx<qS$'),
  ('admin5@example.com', 'O t5QQx<qS\'),
  ('admin6@example.com', 'O t5QQx<qSa'),
  ('admin7@example.com', 'O t5QQx<qS@'),
  ('admin8@example.com', 'O t5QQx<qS`'),
  ('admin9@example.com', 'O t5QQx<qSV'),
  ('admin10@example.com', 'O t5QQx<qSR>'),
  ('admin11@example.com', 'O t5QQx<qSRR'),
  ('admin12@example.com', 'O t5QQx<qSR?'),
  ('admin13@example.com', 'O t5QQx<qSR1'),
  ('admin14@example.com', 'O t5QQx<qSR$'),
  ('admin15@example.com', 'O t5QQx<qSR\'),
  ('admin16@example.com', 'O t5QQx<qSRa'),
  ('admin17@example.com', 'O t5QQx<qSR@'),
  ('admin18@example.com', 'O t5QQx<qSR`'),
  ('admin19@example.com', 'O t5QQx<qSRV'),
  ('admin20@example.com', 'O t5QQx<qS?>'),
  ('admin21@example.com', 'O t5QQx<qS?R'),
  ('admin22@example.com', 'O t5QQx<qS??'),
  ('admin23@example.com', 'O t5QQx<qS?1'),
  ('admin24@example.com', 'O t5QQx<qS?$'),
  ('admin25@example.com', 'O t5QQx<qS?\'),
  ('admin26@example.com', 'O t5QQx<qS?a'),
  ('admin27@example.com', 'O t5QQx<qS?@'),
  ('admin28@example.com', 'O t5QQx<qS?`'),
  ('admin29@example.com', 'O t5QQx<qS?V'),
  ('admin30@example.com', 'O t5QQx<qS1>'),
  ('admin31@example.com', 'O t5QQx<qS1R'),
  ('admin32@example.com', 'O t5QQx<qS1?'),
  ('admin33@example.com', 'O t5QQx<qS11'),
  ('admin34@example.com', 'O t5QQx<qS1$'),
  ('admin35@example.com', 'O t5QQx<qS\'),
  ('admin36@example.com', 'O t5QQx<qS1a'),
  ('admin37@example.com', 'O t5QQx<qS1@'),
  ('admin38@example.com', 'O t5QQx<qS1`'),
  ('admin39@example.com', 'O t5QQx<qS1V'),
  ('admin40@example.com', 'O t5QQx<qS$>'),
  ('admin41@example.com', 'O t5QQx<qS$R'),
  ('admin42@example.com', 'O t5QQx<qS$?'),
  ('admin43@example.com', 'O t5QQx<qS$1'),
  ('admin44@example.com', 'O t5QQx<qS$$'),
  ('admin45@example.com', 'O t5QQx<qS$\'),
  ('admin46@example.com', 'O t5QQx<qS$a'),
  ('admin47@example.com', 'O t5QQx<qS$@'),
  ('admin48@example.com', 'O t5QQx<qS$`'),
  ('admin49@example.com', 'O t5QQx<qS$V'),
  ('admin50@example.com', 'O t5QQx<qS\>');