ALTER TABLE leitura DISABLE TRIGGER ALL;
ALTER TABLE mensagem DISABLE TRIGGER ALL;
ALTER TABLE preco DISABLE TRIGGER ALL;
ALTER TABLE reserva DISABLE TRIGGER ALL;
ALTER TABLE viagem DISABLE TRIGGER ALL;